config/routes.rb
Rails.application.routes.draw do
  resources :user_tasks

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", as: :signout
  get '/signin' => "sessions#new", as: :signin

  root 'user_tasks#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_tasks, dependent: :destroy

  # Creates user using the hash that is returned from the Facebook API
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

  # Pull profile photo in
  def small_image
    "http://graph.facebook.com/#{uid}/picture?type=small"
  end

  def normal_image
    "http://graph.facebook.com/#{uid}/picture?type=normal"
  end
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :description, :due
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  # To make this accessible as a "helper method", we need to declare as a helper_method. This makes it available to the controller AND the view
  helper_method :current_user

  def authenticate_user!
    redirect_to :signin unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  # Log in
  def create
    auth = request.env["omniauth.auth"]

    # Go find the user. If they do not exist yet, create them.
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)

    # Save the user_id in the session
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in successfully!"
  end

  # Log out
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Log out successful."
  end
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :set_user_task, only: [:show, :edit, :update, :destroy]
  before_action :set_all_tasks, only: [:index, :create, :update, :destroy]
  before_action :authenticate_user!
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_task

  # GET /user_tasks
  # GET /user_tasks.json
  def index
  end

  # GET /user_tasks/1
  # GET /user_tasks/1.json
  def show
  end

  # GET /user_tasks/new
  def new
    @user_task = UserTask.new
  end

  # GET /user_tasks/1/edit
  def edit
  end

  # POST /user_tasks
  # POST /user_tasks.json
  def create
    @user_task = current_user.user_tasks.build(user_task_params)

    respond_to do |format|
      if @user_task.save
        format.html { redirect_to @user_task, notice: 'User task was successfully created.' }
        format.js {}
        format.json { render :show, status: :created, location: @user_task }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tasks/1
  # PATCH/PUT /user_tasks/1.json
  def update
    respond_to do |format|
      if @user_task.update(user_task_params)
        format.html { redirect_to @user_task, notice: 'User task was successfully updated.' }
        format.js {}
        format.json { render :show, status: :ok, location: @user_task }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_tasks/1
  # DELETE /user_tasks/1.json
  def destroy
    @user_task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url, notice: 'User task was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private
    def set_all_tasks
      @user_tasks = current_user.user_tasks.order(:due)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user_task
      @user_task = current_user.user_tasks.find(params[:id])
    end

    def invalid_task
      logger.error "Attempt to access invalid task #{params[:id]}"
      redirect_to user_tasks_url, notice: "Invalid task. Access denied."
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_task_params
      params.require(:user_task).permit(:description, :due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/_auth_links.html.erb
<% unless current_page?(signin_path) %>
  <div class="text-right">
    <% if current_user %>
      <%= image_tag current_user.small_image %>
      <%= link_to fa_icon('sign-out', text: 'Sign Out'), signout_path, id: 'sign_out' %>
    <% else %>
      <%= link_to fa_icon('sign-in', text: 'Sign In With Facebook'), '/auth/facebook', id: 'sign_in' %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= render 'layouts/auth_links' %>
  <%= yield %>
</div>

</body>
</html>

app/views/user_tasks/_datepicker.js.erb
$(document).ready(function(){
  $('#user_task_due').datepicker({
    format: "yyyy-mm-dd",
    todayBtn: true,
    autoclose: true,
    todayHighlight: true
  });
});

app/views/user_tasks/_form.html.erb
<%= simple_form_for(@user_task, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  <div class="row">
    <div class="col-sm-6">
      <%= f.input :description, placeholder: "Make groceries." %>
    </div>
    <div class="col-sm-3">
      <%= f.input :due, as: :string, placeholder: "Today!" %>
    </div>
    <div class="col-sm-3">
      <%= f.button :submit, "Save", class: 'btn btn-block btn-success' %>
    </div>
  </div>
  </div>
<% end %>

app/views/user_tasks/_user_task.html.erb
<div class="well">
  <p class="pull-right">
    <em><%= user_task.due.stamp('Thursday, January 1, 2015') %></em>
  </p>
  <p>
    <%= link_to fa_icon('square-o', text: user_task.description), user_task, remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'task-item' %>
    <%= link_to fa_icon('pencil', text: 'Edit'), edit_user_task_path(user_task), remote: true, class: 'edit-task' %>
  </p>
</div>

app/views/user_tasks/create.js.erb
$('#task-form').slideUp(350);
$('#tasks').html("<%= j (render @user_tasks) %>");

app/views/user_tasks/destroy.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");

app/views/user_tasks/edit.html.erb
<h1>Editing User Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_task %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/edit.js.erb
$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);

<%= render 'datepicker' %>

app/views/user_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Todo List</h1>

<%= link_to fa_icon('plus', text: 'Add Task'), new_user_task_path, remote: true, class: 'btn btn-primary' %>
<div id="task-form"></div>

<div id="tasks">
  <%= render @user_tasks %>
</div>

app/views/user_tasks/new.html.erb
<h1>New User Task</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/new.js.erb
$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);

<%= render 'datepicker' %>

app/views/user_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @user_task.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @user_task.due %>
</p>

<%= link_to 'Edit', edit_user_task_path(@user_task) %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/update.js.erb
$('#task-form').slideUp(350);
$('#tasks').html("<%= j (render @user_tasks) %>");